"""
=================================================================================
DeBERTa Binary Classification Pipeline
=================================================================================
Task:       Binary text classification (positive / negative)
Model:      microsoft/deberta-v3-base
Data:       40K synthetic samples from 400 base samples, generated by 10 LLMs
Strategy:   Group-stratified splits (no base_id leakage), chunked long texts,
            Optuna hyperparameter search, save best model for inference.

Usage:
    # 1. Hyperparameter search (finds best config)
    python deberta_binary_pipeline.py --mode search --data_path data.csv

    # 2. Train final model with best config
    python deberta_binary_pipeline.py --mode train --data_path data.csv

    # 3. Run inference
    python deberta_binary_pipeline.py --mode inference --data_path new_data.csv

    # Full auto: search → train → save (recommended first run)
    python deberta_binary_pipeline.py --mode full --data_path data.csv
=================================================================================
"""

import os
import sys
import json
import random
import argparse
import warnings
import re
import unicodedata
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, List, Tuple, Any
from datetime import datetime
from collections import defaultdict

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    set_seed as hf_set_seed,
)
from datasets import Dataset as HFDataset, DatasetDict

from sklearn.model_selection import StratifiedGroupKFold, train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
)

try:
    import optuna
    OPTUNA_AVAILABLE = True
except ImportError:
    OPTUNA_AVAILABLE = False
    warnings.warn("optuna not installed. Run: pip install optuna")

warnings.filterwarnings("ignore")


# =============================================================================
# SECTION 1: CONFIGURATION
# =============================================================================

def set_seed(seed: int = 42):
    """Lock down all sources of randomness."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ["PYTHONHASHSEED"] = str(seed)
    hf_set_seed(seed)


@dataclass
class Config:
    """
    Single source of truth for every setting in the pipeline.
    Override via CLI args or by editing defaults here.
    """

    # -- Model --
    model_name: str = "microsoft/deberta-v3-base"
    num_labels: int = 2

    # -- Data columns --
    text_column: str = "text"
    label_column: str = "label"
    base_id_column: str = "base_id"          # tracks parent sample

    # -- Data paths --
    data_path: str = "data.csv"
    output_dir: str = "./results"

    # -- Chunking (handles texts > 512 tokens) --
    max_length: int = 512                     # DeBERTa hard max
    chunk_overlap: int = 128                  # overlap between windows
    # During inference, probabilities across chunks are mean-pooled.

    # -- Cleaning --
    replace_urls: bool = True
    replace_emails: bool = True
    min_text_length: int = 3                  # minimum word count
    remove_duplicates: bool = True

    # -- Splits --
    train_ratio: float = 0.70
    val_ratio: float = 0.15
    test_ratio: float = 0.15

    # -- Training --
    num_epochs: int = 4
    batch_size: int = 32
    learning_rate: float = 2e-5
    weight_decay: float = 0.01
    warmup_ratio: float = 0.1
    dropout: float = 0.1
    fp16: bool = True
    bf16: bool = False
    gradient_accumulation_steps: int = 1
    max_grad_norm: float = 1.0
    gradient_checkpointing: bool = False

    # -- Evaluation & checkpointing --
    eval_strategy: str = "steps"
    eval_steps: int = 100
    save_strategy: str = "steps"
    save_steps: int = 100
    save_total_limit: int = 3
    load_best_model_at_end: bool = True
    metric_for_best_model: str = "eval_f1"
    greater_is_better: bool = True
    early_stopping_patience: int = 3

    # -- Logging --
    logging_steps: int = 50
    report_to: str = "none"                   # "wandb", "tensorboard", or "none"

    # -- Optuna --
    n_trials: int = 15
    cv_folds: int = 3                         # folds for search (3 = fast, 5 = thorough)

    # -- Class imbalance --
    use_class_weights: bool = True        # weight loss by inverse class freq
    flag_threshold: float = 0.5           # decision threshold (tuned after training)

    # -- Misc --
    seed: int = 42
    dataloader_num_workers: int = 4
    device: str = "cuda" if torch.cuda.is_available() else "cpu"

    def __post_init__(self):
        assert abs(self.train_ratio + self.val_ratio + self.test_ratio - 1.0) < 1e-6
        Path(self.output_dir).mkdir(parents=True, exist_ok=True)

    def save(self, path: str):
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=2)

    @classmethod
    def load(cls, path: str) -> "Config":
        with open(path) as f:
            return cls(**json.load(f))


# =============================================================================
# SECTION 2: TEXT CLEANING
# =============================================================================

class TextCleaner:
    """
    Stateless text preprocessing.  Call TextCleaner.clean(text).
    Order: unicode → html → urls/emails → whitespace → length filter.
    """

    @staticmethod
    def clean(
        text: str,
        min_length: int = 3,
        replace_urls: bool = True,
        replace_emails: bool = True,
    ) -> str:
        if not isinstance(text, str) or pd.isna(text):
            return ""

        # 1. unicode normalisation
        text = unicodedata.normalize("NFKC", text)

        # 2. strip html
        text = re.sub(r"<[^>]+>", "", text)
        text = re.sub(r"&\w+;", "", text)

        # 3. urls & emails
        if replace_urls:
            text = re.sub(r"http\S+|www\.\S+", "[URL]", text)
        if replace_emails:
            text = re.sub(r"\S+@\S+", "[EMAIL]", text)

        # 4. whitespace
        text = re.sub(r"\s+", " ", text).strip()

        # 5. length gate
        if len(text.split()) < min_length:
            return ""

        return text


# =============================================================================
# SECTION 3: GROUP-STRATIFIED DATA SPLITTING
# =============================================================================

def group_stratified_split(
    df: pd.DataFrame,
    label_col: str,
    group_col: str,
    train_ratio: float,
    val_ratio: float,
    seed: int,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Split so that NO base_id appears in more than one partition.

    Strategy:
      1. Collapse to one row per base_id (majority label for stratification).
      2. Stratified-split the base_ids into train / val / test.
      3. Expand back to full rows.

    This prevents data leakage between synthetic siblings.
    """
    # one row per group: take majority label for stratification key
    group_df = (
        df.groupby(group_col)[label_col]
        .agg(lambda x: x.mode().iloc[0])
        .reset_index()
        .rename(columns={label_col: "_strat_label"})
    )

    # first cut: train vs (val+test)
    holdout_ratio = 1.0 - train_ratio
    train_groups, temp_groups = train_test_split(
        group_df,
        test_size=holdout_ratio,
        random_state=seed,
        stratify=group_df["_strat_label"],
    )

    # second cut: val vs test
    val_share = val_ratio / (val_ratio + (1.0 - train_ratio - val_ratio))
    val_groups, test_groups = train_test_split(
        temp_groups,
        test_size=(1.0 - val_share),
        random_state=seed,
        stratify=temp_groups["_strat_label"],
    )

    train_ids = set(train_groups[group_col])
    val_ids = set(val_groups[group_col])
    test_ids = set(test_groups[group_col])

    # sanity: no overlap
    assert train_ids.isdisjoint(val_ids) and train_ids.isdisjoint(test_ids)

    train_df = df[df[group_col].isin(train_ids)].reset_index(drop=True)
    val_df = df[df[group_col].isin(val_ids)].reset_index(drop=True)
    test_df = df[df[group_col].isin(test_ids)].reset_index(drop=True)

    return train_df, val_df, test_df


# =============================================================================
# SECTION 4: CHUNKED TOKENISATION
# =============================================================================

def tokenize_with_chunks(
    texts: List[str],
    labels: List[int],
    tokenizer,
    max_length: int = 512,
    overlap: int = 128,
    doc_ids: Optional[List[int]] = None,
) -> dict:
    """
    Tokenise a list of texts.  Texts longer than max_length are split into
    overlapping windows so that NO content is discarded.

    Returns a dict with:
      input_ids, attention_mask, labels        – for Trainer
      doc_id                                   – maps each chunk back to its
                                                 parent row (needed for
                                                 aggregation at eval time)
    """
    all_input_ids = []
    all_attention_mask = []
    all_labels = []
    all_doc_ids = []

    stride = max_length - overlap  # how far each window advances

    for idx, (text, label) in enumerate(zip(texts, labels)):
        encoded = tokenizer(
            text,
            add_special_tokens=False,  # we'll add them per chunk
            return_attention_mask=False,
        )
        token_ids = encoded["input_ids"]

        # If short enough, single chunk (most common path)
        if len(token_ids) <= max_length - 2:  # room for [CLS] + [SEP]
            chunk_enc = tokenizer(
                text,
                max_length=max_length,
                padding="max_length",
                truncation=True,
            )
            all_input_ids.append(chunk_enc["input_ids"])
            all_attention_mask.append(chunk_enc["attention_mask"])
            all_labels.append(label)
            all_doc_ids.append(doc_ids[idx] if doc_ids else idx)
        else:
            # Sliding window over raw token ids
            for start in range(0, len(token_ids), stride):
                end = start + max_length - 2  # reserve for special tokens
                chunk_tokens = token_ids[start:end]

                # Build chunk with special tokens
                chunk_ids = (
                    [tokenizer.cls_token_id]
                    + chunk_tokens
                    + [tokenizer.sep_token_id]
                )
                attn = [1] * len(chunk_ids)

                # Pad
                pad_len = max_length - len(chunk_ids)
                chunk_ids += [tokenizer.pad_token_id] * pad_len
                attn += [0] * pad_len

                all_input_ids.append(chunk_ids)
                all_attention_mask.append(attn)
                all_labels.append(label)
                all_doc_ids.append(doc_ids[idx] if doc_ids else idx)

                # Stop if we've covered the end
                if end >= len(token_ids):
                    break

    return {
        "input_ids": all_input_ids,
        "attention_mask": all_attention_mask,
        "labels": all_labels,
        "doc_id": all_doc_ids,
    }


def build_hf_dataset(chunk_dict: dict) -> HFDataset:
    """Convert the chunked dict into a HuggingFace Dataset for Trainer."""
    ds = HFDataset.from_dict({
        "input_ids": chunk_dict["input_ids"],
        "attention_mask": chunk_dict["attention_mask"],
        "labels": chunk_dict["labels"],
        "doc_id": chunk_dict["doc_id"],
    })
    ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
    return ds


# =============================================================================
# SECTION 5: METRICS
# =============================================================================

def compute_metrics(eval_pred) -> Dict[str, float]:
    """
    Chunk-level metrics used during training.
    (Document-level aggregation happens in the final evaluation step.)
    """
    logits, labels = eval_pred
    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    preds = np.argmax(logits, axis=-1)

    return {
        "accuracy": float(accuracy_score(labels, preds)),
        "f1": float(f1_score(labels, preds, average="binary", pos_label=1)),
        "precision": float(precision_score(labels, preds, average="binary", pos_label=1)),
        "recall": float(recall_score(labels, preds, average="binary", pos_label=1)),
        "auc_roc": float(roc_auc_score(labels, probs[:, 1])),
    }


def document_level_evaluate(
    trainer: Trainer,
    dataset: HFDataset,
    doc_ids: List[int],
    true_labels: List[int],
    split_name: str = "Test",
    threshold: float = 0.5,
) -> Dict[str, float]:
    """
    Aggregate chunk predictions back to document level via mean-pooling,
    then compute metrics on the full documents — not individual chunks.

    This is the honest evaluation: one prediction per original text row.
    """
    print(f"\n{'=' * 70}")
    print(f"  DOCUMENT-LEVEL EVALUATION  —  {split_name.upper()}  (threshold={threshold:.2f})")
    print(f"{'=' * 70}")

    output = trainer.predict(dataset)
    logits = output.predictions
    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()

    # Group chunks by doc_id, mean-pool probabilities
    doc_probs = defaultdict(list)
    for doc_id, prob in zip(doc_ids, probs):
        doc_probs[doc_id].append(prob)

    # Build document-level predictions in original order
    unique_docs = sorted(doc_probs.keys())
    doc_pred_probs = []
    doc_true = []
    for doc_id in unique_docs:
        mean_prob = np.mean(doc_probs[doc_id], axis=0)
        doc_pred_probs.append(mean_prob)
        # true label: same for all chunks of a doc, take first
        idx = doc_ids.index(doc_id)
        doc_true.append(true_labels[idx])

    doc_pred_probs = np.array(doc_pred_probs)
    # Apply threshold: flag as positive if P(positive) >= threshold
    doc_preds = (doc_pred_probs[:, 1] >= threshold).astype(int)
    doc_true = np.array(doc_true)

    acc = accuracy_score(doc_true, doc_preds)
    f1 = f1_score(doc_true, doc_preds, average="binary", pos_label=1)
    prec = precision_score(doc_true, doc_preds, average="binary", pos_label=1)
    rec = recall_score(doc_true, doc_preds, average="binary", pos_label=1)
    auc = roc_auc_score(doc_true, doc_pred_probs[:, 1])

    results = {
        "accuracy": acc, "f1": f1, "precision": prec,
        "recall": rec, "auc_roc": auc, "threshold": threshold,
    }

    print(f"\n  Documents evaluated : {len(unique_docs)}")
    for name, val in results.items():
        print(f"  {name:20s}: {val:.4f}")

    print(f"\n  Classification Report:")
    print(classification_report(
        doc_true, doc_preds,
        target_names=["negative", "positive"], digits=4,
    ))

    cm = confusion_matrix(doc_true, doc_preds)
    print(f"  Confusion Matrix:")
    print(f"  {cm}\n")

    return results


# =============================================================================
# SECTION 5b: WEIGHTED TRAINER  (handles class imbalance)
# =============================================================================

class WeightedTrainer(Trainer):
    """
    Custom Trainer that applies inverse-frequency class weights to the
    cross-entropy loss.  The minority class (positive) gets a higher
    weight so the model pays more attention to it.
    """

    def __init__(self, class_weights: torch.Tensor = None, **kwargs):
        super().__init__(**kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        if self.class_weights is not None:
            weight = self.class_weights.to(logits.device)
            loss_fn = torch.nn.CrossEntropyLoss(weight=weight)
        else:
            loss_fn = torch.nn.CrossEntropyLoss()

        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss


def compute_class_weights(labels: List[int]) -> torch.Tensor:
    """
    Compute inverse-frequency weights so that the minority class
    contributes equally to the loss.

    With 60% negative / 40% positive:
      negative weight ≈ 0.83,  positive weight ≈ 1.25
    The model is penalised more for missing a positive.
    """
    counts = np.bincount(labels)
    total = len(labels)
    weights = total / (len(counts) * counts)
    weights = weights / weights.sum() * len(counts)  # normalise
    print(f"  Class weights: {dict(enumerate(np.round(weights, 3)))}")
    return torch.tensor(weights, dtype=torch.float32)


# =============================================================================
# SECTION 5c: THRESHOLD TUNING  (optimise for flagging)
# =============================================================================

def tune_threshold(
    trainer: Trainer,
    dataset: HFDataset,
    doc_ids: List[int],
    true_labels: List[int],
    optimize_for: str = "f1",
    min_recall: Optional[float] = None,
) -> float:
    """
    Sweep thresholds on the validation set to find the optimal one.

    Args:
        optimize_for: "f1" (balanced) or "recall" (catch everything)
        min_recall: if set, only consider thresholds that achieve at
                    least this recall (e.g. 0.90 = miss at most 10%)

    Returns the best threshold.
    """
    print(f"\n{'=' * 70}")
    print("  THRESHOLD TUNING")
    print(f"{'=' * 70}")

    output = trainer.predict(dataset)
    probs = torch.softmax(torch.tensor(output.predictions), dim=-1).numpy()

    # Aggregate to document level
    doc_probs_map = defaultdict(list)
    for doc_id, prob in zip(doc_ids, probs):
        doc_probs_map[doc_id].append(prob)

    unique_docs = sorted(doc_probs_map.keys())
    doc_pos_probs = []
    doc_true = []
    for doc_id in unique_docs:
        doc_pos_probs.append(np.mean(doc_probs_map[doc_id], axis=0)[1])
        idx = doc_ids.index(doc_id)
        doc_true.append(true_labels[idx])

    doc_pos_probs = np.array(doc_pos_probs)
    doc_true = np.array(doc_true)

    # Sweep
    best_thresh, best_score = 0.5, 0.0
    print(f"\n  {'Thresh':>8s}  {'Prec':>6s}  {'Recall':>6s}  {'F1':>6s}  {'Note'}")
    print(f"  {'─' * 45}")

    for thresh in np.arange(0.20, 0.80, 0.025):
        preds = (doc_pos_probs >= thresh).astype(int)
        if preds.sum() == 0:
            continue
        p = precision_score(doc_true, preds, pos_label=1, zero_division=0)
        r = recall_score(doc_true, preds, pos_label=1, zero_division=0)
        f = f1_score(doc_true, preds, pos_label=1, zero_division=0)

        if min_recall and r < min_recall:
            note = "  (below min_recall)"
        else:
            note = ""
            score = f if optimize_for == "f1" else r
            if score > best_score:
                best_score = score
                best_thresh = thresh
                note = "  ← best"

        print(f"  {thresh:>8.3f}  {p:>6.3f}  {r:>6.3f}  {f:>6.3f}{note}")

    print(f"\n  Selected threshold: {best_thresh:.3f}  "
          f"(optimized for {optimize_for}, score={best_score:.4f})")

    return float(best_thresh)


# =============================================================================
# SECTION 6: CORE TRAINING FUNCTION
# =============================================================================

def run_training(
    config: Config,
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    test_df: Optional[pd.DataFrame] = None,
    trial_tag: str = "",
) -> Tuple[Trainer, Dict]:
    """
    Train a single model given train/val dataframes.
    Optionally evaluate on test_df.  Returns (trainer, metrics).
    """
    set_seed(config.seed)

    # -- tokenizer --
    tokenizer = AutoTokenizer.from_pretrained(config.model_name)

    # -- tokenize with chunking --
    print(f"\n  Tokenizing train ({len(train_df)} rows) ...")
    train_chunks = tokenize_with_chunks(
        texts=train_df[config.text_column].tolist(),
        labels=train_df[config.label_column].tolist(),
        tokenizer=tokenizer,
        max_length=config.max_length,
        overlap=config.chunk_overlap,
    )
    train_ds = build_hf_dataset(train_chunks)
    print(f"    → {len(train_ds)} chunks (from {len(train_df)} documents)")

    print(f"  Tokenizing val ({len(val_df)} rows) ...")
    val_chunks = tokenize_with_chunks(
        texts=val_df[config.text_column].tolist(),
        labels=val_df[config.label_column].tolist(),
        tokenizer=tokenizer,
        max_length=config.max_length,
        overlap=config.chunk_overlap,
    )
    val_ds = build_hf_dataset(val_chunks)
    print(f"    → {len(val_ds)} chunks (from {len(val_df)} documents)")

    # -- model --
    model = AutoModelForSequenceClassification.from_pretrained(
        config.model_name,
        num_labels=config.num_labels,
        hidden_dropout_prob=config.dropout,
        attention_probs_dropout_prob=config.dropout,
    )

    tag = trial_tag or datetime.now().strftime("%Y%m%d_%H%M%S")
    run_output = os.path.join(config.output_dir, tag)

    training_args = TrainingArguments(
        output_dir=run_output,
        num_train_epochs=config.num_epochs,
        per_device_train_batch_size=config.batch_size,
        per_device_eval_batch_size=config.batch_size * 2,
        learning_rate=config.learning_rate,
        weight_decay=config.weight_decay,
        warmup_ratio=config.warmup_ratio,
        fp16=config.fp16,
        bf16=config.bf16,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        max_grad_norm=config.max_grad_norm,
        gradient_checkpointing=config.gradient_checkpointing,
        eval_strategy=config.eval_strategy,
        eval_steps=config.eval_steps if config.eval_strategy == "steps" else None,
        save_strategy=config.save_strategy,
        save_steps=config.save_steps if config.save_strategy == "steps" else None,
        save_total_limit=config.save_total_limit,
        load_best_model_at_end=config.load_best_model_at_end,
        metric_for_best_model=config.metric_for_best_model,
        greater_is_better=config.greater_is_better,
        logging_steps=config.logging_steps,
        report_to=config.report_to if config.report_to != "none" else [],
        seed=config.seed,
        dataloader_num_workers=config.dataloader_num_workers,
        remove_unused_columns=True,
    )

    # -- class weights for imbalanced data --
    class_weights = None
    if config.use_class_weights:
        class_weights = compute_class_weights(train_chunks["labels"])

    trainer = WeightedTrainer(
        class_weights=class_weights,
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[
            EarlyStoppingCallback(early_stopping_patience=config.early_stopping_patience)
        ],
    )

    # -- train --
    trainer.train()

    # -- val metrics (chunk-level, used for model selection) --
    val_metrics = trainer.evaluate(val_ds)

    # -- threshold tuning on validation set --
    threshold = config.flag_threshold
    threshold = tune_threshold(
        trainer=trainer,
        dataset=val_ds,
        doc_ids=val_chunks["doc_id"],
        true_labels=val_chunks["labels"],
        optimize_for="f1",       # change to "recall" if you want to catch more
        min_recall=None,         # set e.g. 0.90 to enforce minimum recall
    )

    # -- test evaluation (document-level, honest numbers, tuned threshold) --
    test_results = {}
    if test_df is not None:
        test_chunks = tokenize_with_chunks(
            texts=test_df[config.text_column].tolist(),
            labels=test_df[config.label_column].tolist(),
            tokenizer=tokenizer,
            max_length=config.max_length,
            overlap=config.chunk_overlap,
        )
        test_ds = build_hf_dataset(test_chunks)

        test_results = document_level_evaluate(
            trainer=trainer,
            dataset=test_ds,
            doc_ids=test_chunks["doc_id"],
            true_labels=test_chunks["labels"],
            split_name="Test",
            threshold=threshold,
        )

    return trainer, {
        **val_metrics,
        "tuned_threshold": threshold,
        **{f"test_{k}": v for k, v in test_results.items()},
    }


# =============================================================================
# SECTION 7: HYPERPARAMETER SEARCH  (OPTUNA)
# =============================================================================

def run_search(config: Config, df: pd.DataFrame) -> dict:
    """
    Bayesian hyperparameter search with Optuna.

    Each trial trains on a group-stratified train/val split (no base_id
    leakage) and returns the validation F1.  The best params are saved
    to disk and returned.
    """
    if not OPTUNA_AVAILABLE:
        raise ImportError("Install optuna:  pip install optuna")

    print("\n" + "=" * 70)
    print("  HYPERPARAMETER SEARCH")
    print("=" * 70)
    print(f"  Trials        : {config.n_trials}")
    print(f"  CV folds      : {config.cv_folds}")
    print(f"  Search space  : lr, batch_size, epochs, warmup, weight_decay, dropout")

    # Pre-split: hold out a true test set that is NEVER seen during search
    train_val_df, test_df = _split_train_test(df, config)

    def objective(trial: optuna.Trial) -> float:
        # -- sample hyperparameters --
        lr = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
        bs = trial.suggest_categorical("batch_size", [16, 32])
        epochs = trial.suggest_int("num_epochs", 3, 5)
        warmup = trial.suggest_float("warmup_ratio", 0.05, 0.20)
        wd = trial.suggest_float("weight_decay", 0.005, 0.05)
        dropout = trial.suggest_float("dropout", 0.05, 0.20)

        trial_config = Config(
            **{
                **asdict(config),
                "learning_rate": lr,
                "batch_size": bs,
                "num_epochs": epochs,
                "warmup_ratio": warmup,
                "weight_decay": wd,
                "dropout": dropout,
                "report_to": "none",
                "eval_strategy": "epoch",
                "save_strategy": "epoch",
            }
        )

        # -- grouped CV on the train_val portion --
        groups = train_val_df[config.base_id_column].values
        labels = train_val_df[config.label_column].values
        sgkf = StratifiedGroupKFold(
            n_splits=config.cv_folds, shuffle=True, random_state=config.seed
        )

        fold_scores = []
        for fold_i, (train_idx, val_idx) in enumerate(sgkf.split(train_val_df, labels, groups)):
            print(f"\n  Trial {trial.number} / Fold {fold_i + 1}")
            fold_train = train_val_df.iloc[train_idx].reset_index(drop=True)
            fold_val = train_val_df.iloc[val_idx].reset_index(drop=True)

            try:
                _, metrics = run_training(
                    trial_config,
                    fold_train,
                    fold_val,
                    test_df=None,
                    trial_tag=f"search/trial_{trial.number}_fold_{fold_i}",
                )
                f1_val = metrics.get("eval_f1", 0.0)
                fold_scores.append(f1_val)
            except Exception as e:
                print(f"  ⚠  Fold failed: {e}")
                fold_scores.append(0.0)

        mean_f1 = float(np.mean(fold_scores))
        print(f"\n  Trial {trial.number}  →  mean F1 = {mean_f1:.4f}  (folds: {fold_scores})")
        return mean_f1

    study = optuna.create_study(direction="maximize", study_name="deberta_search")
    study.optimize(objective, n_trials=config.n_trials, show_progress_bar=True)

    # -- report --
    print("\n" + "=" * 70)
    print("  SEARCH COMPLETE")
    print("=" * 70)
    print(f"  Best trial   : {study.best_trial.number}")
    print(f"  Best F1 (CV) : {study.best_value:.4f}")
    print(f"  Best params  :")
    for k, v in study.best_params.items():
        print(f"    {k:20s}: {v}")

    # -- save --
    best_path = Path(config.output_dir) / "best_hyperparameters.json"
    with open(best_path, "w") as f:
        json.dump(
            {"best_f1_cv": study.best_value, "params": study.best_params},
            f, indent=2,
        )
    print(f"\n  Saved to {best_path}")

    return study.best_params


def _split_train_test(df, config):
    """
    Quick group-stratified split into train_val (85%) and test (15%)
    for use during search.  The test set is untouched until final eval.
    """
    group_df = (
        df.groupby(config.base_id_column)[config.label_column]
        .agg(lambda x: x.mode().iloc[0])
        .reset_index()
        .rename(columns={config.label_column: "_strat"})
    )
    tv_groups, te_groups = train_test_split(
        group_df, test_size=config.test_ratio,
        stratify=group_df["_strat"], random_state=config.seed,
    )
    tv_ids = set(tv_groups[config.base_id_column])
    te_ids = set(te_groups[config.base_id_column])
    return (
        df[df[config.base_id_column].isin(tv_ids)].reset_index(drop=True),
        df[df[config.base_id_column].isin(te_ids)].reset_index(drop=True),
    )


# =============================================================================
# SECTION 8: FULL TRAINING (BEST PARAMS → FINAL MODEL)
# =============================================================================

def run_final_training(config: Config, df: pd.DataFrame, best_params: Optional[dict] = None):
    """
    Train on the full train split with the best hyperparameters,
    evaluate on test, save the final model for production use.
    """
    print("\n" + "=" * 70)
    print("  FINAL MODEL TRAINING")
    print("=" * 70)

    # Apply best params if provided
    if best_params:
        for k, v in best_params.items():
            if hasattr(config, k):
                setattr(config, k, v)
        print("  Applied best hyperparameters from search.")

    # Group-stratified 3-way split
    train_df, val_df, test_df = group_stratified_split(
        df,
        label_col=config.label_column,
        group_col=config.base_id_column,
        train_ratio=config.train_ratio,
        val_ratio=config.val_ratio,
        seed=config.seed,
    )

    _print_split_summary(train_df, val_df, test_df, config)

    trainer, results = run_training(
        config, train_df, val_df, test_df, trial_tag="final_model"
    )

    # -- save everything --
    model_dir = Path(config.output_dir) / "final_model"
    trainer.save_model(str(model_dir))
    trainer.tokenizer.save_pretrained(str(model_dir))

    # Save threshold so the Classifier can load it automatically
    tuned_threshold = results.get("tuned_threshold", 0.5)
    config.flag_threshold = tuned_threshold
    config.save(str(model_dir / "config.json"))

    threshold_path = model_dir / "threshold.json"
    with open(threshold_path, "w") as f:
        json.dump({"flag_threshold": tuned_threshold}, f, indent=2)

    results_path = Path(config.output_dir) / "final_results.json"
    with open(results_path, "w") as f:
        # filter to JSON-serializable values
        serializable = {k: v for k, v in results.items() if isinstance(v, (int, float, str))}
        json.dump(serializable, f, indent=2)

    print(f"\n  Model saved to  : {model_dir}")
    print(f"  Results saved to: {results_path}")

    return trainer, results


def _print_split_summary(train_df, val_df, test_df, config):
    total = len(train_df) + len(val_df) + len(test_df)
    for name, split in [("Train", train_df), ("Val", val_df), ("Test", test_df)]:
        n = len(split)
        n_groups = split[config.base_id_column].nunique()
        label_dist = split[config.label_column].value_counts().to_dict()
        print(f"  {name:5s}: {n:>6,} rows  |  {n_groups:>3} base IDs  |  "
              f"labels: {label_dist}  ({n/total*100:.1f}%)")


# =============================================================================
# SECTION 9: INFERENCE
# =============================================================================

class Classifier:
    """
    Load a saved model and classify new texts.
    Handles long texts via chunking + probability aggregation automatically.
    """

    def __init__(self, model_dir: str, device: str = None, threshold: float = None):
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.tokenizer = AutoTokenizer.from_pretrained(model_dir)
        self.model = AutoModelForSequenceClassification.from_pretrained(model_dir)
        self.model.to(self.device)
        self.model.eval()

        # Load config if available
        cfg_path = Path(model_dir) / "config.json"
        if cfg_path.exists():
            self.config = Config.load(str(cfg_path))
        else:
            self.config = Config()

        # Load tuned threshold (saved during training)
        if threshold is not None:
            self.threshold = threshold
        else:
            thresh_path = Path(model_dir) / "threshold.json"
            if thresh_path.exists():
                self.threshold = json.loads(thresh_path.read_text())["flag_threshold"]
            else:
                self.threshold = self.config.flag_threshold

        print(f"  Model loaded from {model_dir}  (device={self.device})")
        print(f"  Flag threshold: {self.threshold:.3f}")

    def predict(
        self, texts: List[str], batch_size: int = 64
    ) -> List[Dict[str, Any]]:
        """
        Classify a list of texts using the tuned threshold.

        Returns a list of dicts:
          [{"label": 1, "flagged": True, "confidence": 0.94,
            "prob_positive": 0.94, "probs": [0.06, 0.94]}, ...]

        Long texts are automatically chunked and aggregated.
        """
        # Chunk all texts, tracking which chunks belong to which doc
        all_input_ids, all_attn, all_doc_ids = [], [], []
        for doc_idx, text in enumerate(texts):
            chunks = tokenize_with_chunks(
                texts=[text],
                labels=[0],  # dummy
                tokenizer=self.tokenizer,
                max_length=self.config.max_length,
                overlap=self.config.chunk_overlap,
                doc_ids=[doc_idx],
            )
            all_input_ids.extend(chunks["input_ids"])
            all_attn.extend(chunks["attention_mask"])
            all_doc_ids.extend(chunks["doc_id"])

        # Run inference in batches
        all_probs = []
        for i in range(0, len(all_input_ids), batch_size):
            batch_ids = torch.tensor(all_input_ids[i : i + batch_size]).to(self.device)
            batch_attn = torch.tensor(all_attn[i : i + batch_size]).to(self.device)
            with torch.no_grad():
                logits = self.model(input_ids=batch_ids, attention_mask=batch_attn).logits
            probs = torch.softmax(logits, dim=-1).cpu().numpy()
            all_probs.extend(probs)

        # Aggregate by doc_id
        doc_probs = defaultdict(list)
        for doc_id, prob in zip(all_doc_ids, all_probs):
            doc_probs[doc_id].append(prob)

        results = []
        for doc_idx in range(len(texts)):
            mean_prob = np.mean(doc_probs[doc_idx], axis=0)
            prob_positive = float(mean_prob[1])
            flagged = prob_positive >= self.threshold
            label = 1 if flagged else 0
            results.append({
                "label": label,
                "flagged": flagged,
                "confidence": float(mean_prob[label]),
                "prob_positive": prob_positive,
                "probs": mean_prob.tolist(),
            })

        return results

    def predict_single(self, text: str) -> Dict[str, Any]:
        return self.predict([text])[0]


# =============================================================================
# SECTION 10: DATA LOADING & CLEANING ENTRYPOINT
# =============================================================================

def load_and_clean(config: Config) -> pd.DataFrame:
    """Load data from disk, validate columns, clean text, report stats."""
    print("\n" + "=" * 70)
    print("  LOADING & CLEANING DATA")
    print("=" * 70)

    p = Path(config.data_path)
    if p.suffix == ".csv":
        df = pd.read_csv(p)
    elif p.suffix == ".json":
        df = pd.read_json(p)
    elif p.suffix == ".jsonl":
        df = pd.read_json(p, lines=True)
    elif p.suffix == ".parquet":
        df = pd.read_parquet(p)
    else:
        raise ValueError(f"Unsupported format: {p.suffix}")

    print(f"  Loaded {len(df):,} rows  |  columns: {df.columns.tolist()}")

    # Validate required columns
    for col in [config.text_column, config.label_column, config.base_id_column]:
        assert col in df.columns, f"Missing column: '{col}'"

    # Encode labels if string
    if df[config.label_column].dtype == "object":
        unique = sorted(df[config.label_column].unique())
        label_map = {lab: i for i, lab in enumerate(unique)}
        df[config.label_column] = df[config.label_column].map(label_map)
        print(f"  Mapped labels: {label_map}")
        map_path = Path(config.output_dir) / "label_map.json"
        with open(map_path, "w") as f:
            json.dump(label_map, f, indent=2)

    # Clean
    original_len = len(df)
    df["_clean"] = df[config.text_column].apply(
        lambda t: TextCleaner.clean(
            t,
            min_length=config.min_text_length,
            replace_urls=config.replace_urls,
            replace_emails=config.replace_emails,
        )
    )
    df = df[df["_clean"].str.len() > 0].reset_index(drop=True)
    if config.remove_duplicates:
        df = df.drop_duplicates(subset=["_clean"]).reset_index(drop=True)
    df[config.text_column] = df["_clean"]
    df.drop(columns=["_clean"], inplace=True)

    removed = original_len - len(df)
    print(f"  After cleaning: {len(df):,} rows  (removed {removed:,})")

    # Quick stats
    n_base = df[config.base_id_column].nunique()
    label_dist = df[config.label_column].value_counts().to_dict()
    lengths = df[config.text_column].str.split().str.len()
    pct_long = (lengths > config.max_length).mean() * 100

    print(f"  Base IDs       : {n_base}")
    print(f"  Label dist     : {label_dist}")
    print(f"  Text lengths   : median={lengths.median():.0f}, "
          f"max={lengths.max()}, >512 tokens={pct_long:.1f}%")

    return df


# =============================================================================
# SECTION 11: MAIN  (CLI ENTRYPOINT)
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="DeBERTa Binary Classification")
    parser.add_argument("--mode", choices=["search", "train", "full", "inference"],
                        default="full", help="Pipeline stage to run")
    parser.add_argument("--data_path", type=str, required=True)
    parser.add_argument("--output_dir", type=str, default="./results")
    parser.add_argument("--text_column", type=str, default="text")
    parser.add_argument("--label_column", type=str, default="label")
    parser.add_argument("--base_id_column", type=str, default="base_id")
    parser.add_argument("--n_trials", type=int, default=15)
    parser.add_argument("--cv_folds", type=int, default=3)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--model_dir", type=str, default=None,
                        help="Path to saved model (for inference mode)")
    args = parser.parse_args()

    config = Config(
        data_path=args.data_path,
        output_dir=args.output_dir,
        text_column=args.text_column,
        label_column=args.label_column,
        base_id_column=args.base_id_column,
        n_trials=args.n_trials,
        cv_folds=args.cv_folds,
        seed=args.seed,
    )

    print("\n" + "=" * 70)
    print("  DeBERTa Binary Classification Pipeline")
    print("=" * 70)
    print(f"  Mode    : {args.mode}")
    print(f"  Model   : {config.model_name}")
    print(f"  Device  : {config.device}")
    print(f"  Data    : {config.data_path}")

    # -----------------------------------------------------------
    if args.mode == "search":
        df = load_and_clean(config)
        best_params = run_search(config, df)

    # -----------------------------------------------------------
    elif args.mode == "train":
        df = load_and_clean(config)
        # Load best params if they exist from a prior search
        bp_path = Path(config.output_dir) / "best_hyperparameters.json"
        best_params = None
        if bp_path.exists():
            best_params = json.loads(bp_path.read_text()).get("params")
            print(f"  Loaded best params from {bp_path}")
        run_final_training(config, df, best_params)

    # -----------------------------------------------------------
    elif args.mode == "full":
        df = load_and_clean(config)
        best_params = run_search(config, df)
        run_final_training(config, df, best_params)

    # -----------------------------------------------------------
    elif args.mode == "inference":
        model_dir = args.model_dir or str(Path(config.output_dir) / "final_model")
        clf = Classifier(model_dir)

        df = pd.read_csv(args.data_path)
        assert config.text_column in df.columns

        print(f"\n  Running inference on {len(df):,} rows ...")
        preds = clf.predict(df[config.text_column].tolist())
        df["pred_label"] = [p["label"] for p in preds]
        df["flagged"] = [p["flagged"] for p in preds]
        df["pred_confidence"] = [p["confidence"] for p in preds]
        df["prob_positive"] = [p["prob_positive"] for p in preds]
        df["prob_negative"] = [p["probs"][0] for p in preds]

        n_flagged = df["flagged"].sum()
        print(f"  Flagged: {n_flagged:,} / {len(df):,}  ({n_flagged/len(df)*100:.1f}%)")
        print(f"  Threshold used: {clf.threshold:.3f}")

        out_path = Path(config.output_dir) / "predictions.csv"
        df.to_csv(out_path, index=False)
        print(f"  Predictions saved to {out_path}")

    print("\n  Done.\n")


if __name__ == "__main__":
    main()
